/**
 * Internal Dependencies.
 */
import { Inter } from "next/font/google";
import "../styles/index.css";
import Provider from "../components/provider/index";
import Header from "../components/header/index";
import Footer from "../components/footer/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          <main className="container mx-auto py-4 min-h-50vh">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}

export default RootLayout;
